name: Health Check

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-hjo9.onrender.com/health
